version: '3.8'

services:
  nginx_proxy_manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_proxy_manager
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "81:81" # Admin panel NGINX Proxy Managera
    volumes:
      - ./nginx-data:/data
      - ./nginx-letsencrypt:/etc/letsencrypt

  backend:
    build: ./
    container_name: backend
    restart: always
    environment:
      NODE_ENV: production
      MONGO_URI: "mongodb://admin:secret@mongodb:27017/sensors?authSource=admin"
    expose:
      - "3000"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
